name: 'Test on Linux'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install LibreWolf
        run: |
          sudo apt update && sudo apt install extrepo -y
          sudo extrepo enable librewolf
          sudo apt update && sudo apt install librewolf -y
      - name: Install Brave
        run: |
          curl -fsSL https://dl.brave.com/install.sh | sudo sh
      - name: Install Vivaldi
        run: |
          curl -fsSLO https://downloads.vivaldi.com/stable/vivaldi-stable_7.3.3635.9-1_armhf.deb
          sudo apt install ./vivaldi-stable_7.3.3635.9-1_armhf.deb -y

      - name: Install Opera
        run: |
          https://download5.operacdn.com/ftp/pub/opera/desktop/117.0.5408.197/linux/opera-stable_117.0.5408.197_amd64.deb
          sudo apt install ./opera-stable_117.0.5408.197_amd64.deb -y

      - name: Install patched geckodriver
        run: |
          tag=$(curl -fsSL 'https://api.github.com/repos/rafiibrahim8/geckodriver-unchained/releases/latest' | jq -r '.tag_name')
          mkdir -p ~/.local/bin
          curl -Lo ~/.local/bin/geckodriver "https://github.com/rafiibrahim8/geckodriver-unchained/releases/download/$tag/geckodriver-unchained-linux-$tag"
          chmod +x ~/.local/bin/geckodriver
          echo "GECKOWEBDRIVER=$HOME/.local/bin/geckodriver" >> "$GITHUB_ENV"

      - name: Install Python Dependencies
        run: |
          pip install -r tests/test-requirements.txt
      - name: Set Environment Variables
        run: |
          echo "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus" >> "$GITHUB_ENV"
      - name: Run Browser Tests
        env:
          DBUS_SESSION_BUS_ADDRESS: "${{ env.DBUS_SESSION_BUS_ADDRESS }}"
        run: |
          python -m unittest -v
      - name: Test Build
        run: |
          pip install build
          python -m build
